import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Privacy Policy")),
      body: const Markdown(
        selectable: true,
        padding: EdgeInsets.all(16),
        data: '''
# Privacy Policy

_Last updated: August 2025_

**Tambo 71 LLC** operates the mobile application **Recy.AI** (the "App").  
We are committed to protecting your privacy and ensuring the security of your personal information.  
This Privacy Policy explains what information we collect, how we use it, and your rights regarding that information.

---

## Information We Collect

When you use **Recy.AI**, we may collect the following personally identifiable information:

- **Name** (to personalize your account and challenges)  
- **Profile Picture** (optional, for user identification within the app)  
- **Location Data** (only when required to provide relevant recycling/disposal guidance)  
- **Camera Access** (used solely for analyzing waste items; no images are shared without your consent)  
- **Email Address** (for account creation and login via Firebase Authentication)  
- **User ID** (a unique identifier generated by Firebase Authentication)  

---

## How We Use Your Information

We use the information we collect for the following purposes:

- To **authenticate users** securely through Firebase Authentication.  
- To **analyze waste items** using your camera input and provide guidance on the correct disposal bin.  
- To **improve our services**, features, and user experience.  
- To **personalize challenges and app interactions** with your profile information.  
- To **send important updates and notifications** related to the app.  

---

## Data Storage and Security

Your information is securely stored using **Firebase services**.  
We implement reasonable safeguards to protect your data, but please note that no method of transmission over the internet or method of electronic storage is 100% secure.

---

## Sharing of Information

We **do not sell or rent your personal information**.  
We may share information only in the following cases:  

- With service providers that help us operate the app (e.g., Firebase).  
- If required by law or to comply with a valid legal request.  

---

## Your Rights

You have the right to:  

- Access, update, or delete your personal information.  
- Withdraw consent for data collection (e.g., disable location or camera access).  
- Contact us for any questions or concerns regarding your privacy.  

---

## Contact Us

If you have any questions about this Privacy Policy, please contact us:  

**Tambo 71 LLC**  
Email: dayle@tambo71.com
''',
      ),
    );
  }
}
