// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_mhpabKOxgdEU7STNIBBi0rnFiSC61I',
    appId: '1:1034591139029:web:084f52e84a03a100b51e5c',
    messagingSenderId: '1034591139029',
    projectId: 'ecoscan-5dcdc',
    authDomain: 'ecoscan-5dcdc.firebaseapp.com',
    storageBucket: 'ecoscan-5dcdc.firebasestorage.app',
    measurementId: 'G-ML2D3VJPVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0XlvcDOrl7vRynw872s_Sruo_pjOkHc',
    appId: '1:1034591139029:android:777ecfe2beb9ff13b51e5c',
    messagingSenderId: '1034591139029',
    projectId: 'ecoscan-5dcdc',
    storageBucket: 'ecoscan-5dcdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqnx5XQvy-8b_BS1SfCGAGephZWVLsFY',
    appId: '1:1034591139029:ios:ef5da95b410598b9b51e5c',
    messagingSenderId: '1034591139029',
    projectId: 'ecoscan-5dcdc',
    storageBucket: 'ecoscan-5dcdc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqnx5XQvy-8b_BS1SfCGAGephZWVLsFY',
    appId: '1:1034591139029:ios:ef5da95b410598b9b51e5c',
    messagingSenderId: '1034591139029',
    projectId: 'ecoscan-5dcdc',
    storageBucket: 'ecoscan-5dcdc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY_mhpabKOxgdEU7STNIBBi0rnFiSC61I',
    appId: '1:1034591139029:web:2efc2504eba00973b51e5c',
    messagingSenderId: '1034591139029',
    projectId: 'ecoscan-5dcdc',
    authDomain: 'ecoscan-5dcdc.firebaseapp.com',
    storageBucket: 'ecoscan-5dcdc.firebasestorage.app',
    measurementId: 'G-S3DK6XHSBK',
  );
}
